version: '3'

vars:
  HTTP_PORT: "8080"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  setup:
    desc: Setup project - install dependencies
    cmds:
      - uv pip install --editable .

  setup-dev:
    desc: Setup project with dev dependencies
    cmds:
      - uv pip install --editable ".[dev]"

  check:
    desc: Check code style with ruff
    cmds:
      - uv run ruff check .

  check-fix:
    desc: Check and fix code style issues with ruff
    cmds:
      - uv run ruff check --fix .
      - uv run ruff format .

  format:
    desc: Format code with ruff
    cmds:
      - uv run ruff format .

  test:
    desc: Run tests with pytest
    cmds:
      - uv run pytest

  test-verbose:
    desc: Run tests with verbose output
    cmds:
      - uv run pytest -v

  test-cov:
    desc: Run tests with coverage report
    cmds:
      - uv run pytest --cov

  test-unit:
    desc: Run unit tests only
    cmds:
      - uv run pytest tests/unit -v

  test-integration:
    desc: Run integration tests only
    cmds:
      - uv run pytest tests/integration -v

  lint:
    desc: Run all linting checks (ruff check + format)
    cmds:
      - task: check
      - task: format

  ci:
    desc: Run CI checks (lint + test)
    cmds:
      - task: check
      - task: test

  dev:
    desc: Run MCP server in HTTP mode for local development
    cmds:
      - uv run uvicorn app:app --host 127.0.0.1 --port {{.HTTP_PORT}}

  print-cursor-config:
    desc: Print copy&paste ready config for Cursor local debug
    cmds:
      - |
        echo "{"
        echo '  "mcpServers": {'
        echo '    "TIDAL MCP (HTTP)": {'
        echo '      "url": "http://127.0.0.1:{{.HTTP_PORT}}/mcp",'
        echo '      "transport": "sse"'
        echo "    }"
        echo "  }"
        echo "}"

  docker-build:
    desc: Build Docker image for TIDAL MCP using buildx (for local use)
    cmds:
      - docker buildx build --pull --load -t {{.DOCKER_IMAGE_NAME}}:{{.DOCKER_IMAGE_TAG}} .

  docker-build-cloud:
    desc: Build Docker image for cloud deployment (linux/amd64)
    cmds:
      - docker buildx build --platform linux/amd64 --pull --load -t {{.DOCKER_IMAGE_NAME}}:{{.DOCKER_IMAGE_TAG}} .

  docker-dev:
    desc: Launch TIDAL MCP server using docker-compose for local development
    cmds:
      - docker compose up

